### ISSUE TITLE
Address Sanitation error

### ISSUE THREAD

**Issue by skinkie** [jiangwenyuan/nuster#71]
```
ASAN_OPTIONS="halt_on_error=0" ./haproxy -W -db -f haproxy.cfg 
=================================================================
==169369==ERROR: AddressSanitizer: global-buffer-overflow on address 0x000000b1f0c8 at pc 0x000000707f02 bp 0x7ffcbae814f0 sp 0x7ffcbae814e0
READ of size 8 at 0x000000b1f0c8 thread T0
    #0 0x707f01 in sample_register_fetches src/sample.c:360
    #1 0x6cf11f in main src/haproxy.c:3088
    #2 0x7fb4bf946e3a in __libc_start_main (/lib64/libc.so.6+0x23e3a)
    #3 0x420079 in _start (/mnt/storage/home/skinkie/Sources/nuster/haproxy+0x420079)

0x000000b1f0c8 is located 0 bytes to the right of global variable 'nst_sample_fetch_keywords' defined in 'src/nuster/sample.c:166:35' (0xb1efa0) of size 296
SUMMARY: AddressSanitizer: global-buffer-overflow src/sample.c:360 in sample_register_fetches
Shadow bytes around the buggy address:
  0x00008015bdc0: f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9
  0x00008015bdd0: f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9
  0x00008015bde0: 00 00 00 00 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9
  0x00008015bdf0: f9 f9 f9 f9 00 00 00 00 00 00 00 00 00 00 00 00
  0x00008015be00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x00008015be10: 00 00 00 00 00 00 00 00 00[f9]f9 f9 f9 f9 f9 f9
  0x00008015be20: 00 00 00 00 00 00 00 00 f9 f9 f9 f9 f9 f9 f9 f9
  0x00008015be30: f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9
  0x00008015be40: f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9
  0x00008015be50: f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9
  0x00008015be60: f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
```
I noticed that this error does not happen in the master branch of haproxy.

**Comment by jiangwenyuan** [comment]
@skinkie fixed in https://github.com/jiangwenyuan/nuster/commit/579582cdb7410ee8f49f8247a020dc8c44f22769

Can you confirm?
Thanks

**Comment by skinkie** [comment]
It looked so promising (since the minor memory leak was also gone) that I started to wonder if ASAN actually worked by removing your patch ;-)

Confirmed: this works. Good job.

**Comment by jiangwenyuan** [comment]
Thanks
